name: calc
version: 0.1.0.0
github: "githubuser/calc"
license: BSD3
author: "Gabrijel Boduljak"
maintainer: "boduljak.g@gmail.com"
copyright: "2020 Gabrijel Boduljak"

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/githubuser/calc#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  calc:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - calc
